export const GET_HOME_DATA = "GET_HOME_DATA";
export const GET_SINGLE_ALBUM = "GET_SINGLE_ALBUM";
export const GET_SINGLE_PLAYLIST = "GET_SINGLE_PLAYLIST";
export const GET_ARTIST_DETAILS = "GET_ARTIST_DETAILS";
export const GET_ARTIST_SONGS = "GET_ARTIST_SONGS";
export const GET_ARTIST_ALBUMS = "GET_ARTIST_ALBUMS";

export const PLAY_SONG_BEGIN = "PLAY_SONG_BEGIN";
export const PLAY_SONG_SUCESS = "PLAY_SONG_SUCESS";
export const PLAY_SONG_ERROR = "PLAY_SONG_ERROR";
export const SONG_PAUSED = "SONG_PAUSED";
export const SONG_PLAYING = "SONG_PLAYING";
export const RIGHT_MENU_BTN = "RIGHT_MENU_BTN";
export const SEARCH_BEGIN = "SEARCH_BEGIN";
export const SEARCH_SUCESS = "SEARCH_SUCESS";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const NEXT_PAGE_BTN = "NEXT_PAGE_BTN";
export const PREV_PAGE_BTN = "PREV_PAGE_BTN";
export const NEW_SEARCH_BEGIN = "NEW_SEARCH_BEGIN";
export const LEFT_MENU_BTN = "LEFT_MENU_BTN";
export const ALERT_SHOW = "ALERT_SHOW";
export const NEXT_SEARCHED_ARRAY = "NEXT_SEARCHED_ARRAY";
export const NEXT_SEARCHED_ARRAY_ERROR = "NEXT_SEARCHED_ARRAY_ERROR";
export const SEARCH_SONGS_SUCESS = "SEARCH_SONGS_SUCESS";
export const SEARCH_ALBUMS_SUCESS = "SEARCH_ALBUMS_SUCESS";
export const NEXT_SEARCHED_ALBUMS = "NEXT_SEARCHED_ALBUMS";
export const NEXT_PAGE_BTN_ALBUMS = "NEXT_PAGE_BTN_ALBUMS";
export const PLAYING_CURRENT_ALBUM = "PLAYING_CURRENT_ALBUM";
export const PLAYING_CURRENT_ARTIST = "PLAYING_CURRENT_ARIST";
export const PLAYING_CURRENT_PLAYLIST = "PLAYING_CURRENT_PLAYLIST";
export const PLAYING_VIEWALLSONGS_LISTS = "PLAYING_VIEWALLSONGS_LISTS";
export const GET_ALL_PLAYLISTS_BEGIN = "GET_ALL_PLAYLISTS_BEGIN";
export const GET_ALL_PLAYLISTS_SUCCESS = "GET_ALL_PLAYLISTS_SUCCESS";
export const GET_ALL_PLAYLISTS_FAILED = "GET_ALL_PLAYLISTS_FAILED";

export const _onSuccess = (type) => {
  return type + "_SUCCESS";
};

export const _onError = (type) => {
  return type + "_ERROR";
};
